### ISSUE TITLE
Feature - Add support for paid use of `/worksite` or `/setworksite` commands

### ISSUE THREAD

**Issue by dusekdan** [dusekdan/Worksites-Spigot#3]
Likely allow setting up cost for `/delworksite` and `/worksites` as well to make it complete (though the use case does not make much sense to me at this point in time).

**Challenge myself (but not really) part**: This will be best implemented by taking advantage of Vault service design for economy (instead of faking it with allowing user to set which commands should execute in the user context before/after paid command is used). The implementation will be quite straightforward, only obstacle could be using Maven, per usual. 

Price will set in config, like this:
```yaml
enable-paid-commands: true|false
payment-exempts: "permission.node.to.exempt.from.payment" 
command-costs:
    delworksite: 0
    setworksite: 0
    worksite: 100
    worksites: 10
```
